[tox]
skipsdist = True
envlist =
    py3{9,10,11,12}-{module,flake8,lizard,mypy,ruff}
    flake8
    mypy
    ruff
skip_missing_interpreters = True


[testenv:py39-module]
deps = -rrequirements-test.txt
commands =
    python3 -m pytest --cov-config=pyproject.toml --cov=modules --cov-report=html --cov-report=xml --cov-report=term-missing tests

[testenv:py310-module]
deps = -rrequirements-test.txt
commands =
    python3 -m pytest --cov-config=pyproject.toml --cov=modules --cov-report=html --cov-report=xml --cov-report=term-missing tests

[testenv:py311-module]
deps = -rrequirements-test.txt
commands =
    python3 -m pytest --cov-config=pyproject.toml --cov=modules --cov-report=html --cov-report=xml --cov-report=term-missing tests

[testenv:py312-module]
deps = -rrequirements-test.txt
commands =
    python3 -m pytest --cov-config=pyproject.toml --cov=modules --cov-report=html --cov-report=xml --cov-report=term-missing tests

[testenv:flake8]
skip_install = true
deps = -rrequirements-test.txt
commands =
  pflake8 main.py modules_sem

[testenv:py39-flake8]
skip_install = true
deps = -rrequirements-test.txt
commands =
  pflake8 main.py modules_sem

[testenv:py310-flake8]
skip_install = true
deps = -rrequirements-test.txt
commands =
  pflake8 main.py modules_sem

[testenv:py311-flake8]
skip_install = true
deps = -rrequirements-test.txt
commands =
  pflake8 main.py modules_sem

[testenv:py312-flake8]
skip_install = true
deps = -rrequirements-test.txt
commands =
  pflake8 main.py modules_sem

[testenv:lizard]
skip_install = true
deps = -rrequirements-test.txt
commands =
  lizard main.py modules_sem -C 10

[testenv:py39-lizard]
skip_install = true
deps = -rrequirements-test.txt
commands =
  lizard main.py modules_sem -C 10

[testenv:py310-lizard]
skip_install = true
deps = -rrequirements-test.txt
commands =
  lizard main.py modules_sem -C 10

[testenv:py311-lizard]
skip_install = true
deps = -rrequirements-test.txt
commands =
  lizard main.py modules_sem -C 10

[testenv:py312-lizard]
skip_install = true
deps = -rrequirements-test.txt
commands =
  lizard main.py modules_sem -C 10

[testenv:mypy]
skip_install = true
deps = -rrequirements-test.txt
commands =
  mypy main.py modules_sem

[testenv:py39-mypy]
skip_install = true
deps = -rrequirements-test.txt
commands =
  mypy main.py modules_sem

[testenv:py310-mypy]
skip_install = true
deps = -rrequirements-test.txt
commands =
  mypy main.py modules_sem

[testenv:py311-mypy]
skip_install = true
deps = -rrequirements-test.txt
commands =
  mypy main.py modules_sem

[testenv:py312-mypy]
skip_install = true
deps = -rrequirements-test.txt
commands =
  mypy main.py modules_sem

[testenv:ruff]
skip_install = true
deps = -rrequirements-test.txt
commands =
  ruff check main.py modules_sem

[testenv:py39-ruff]
skip_install = true
deps = -rrequirements-test.txt
commands =
  ruff check main.py modules_sem

[testenv:py310-ruff]
skip_install = true
deps = -rrequirements-test.txt
commands =
  ruff check main.py modules_sem

[testenv:py311-ruff]
skip_install = true
deps = -rrequirements-test.txt
commands =
  ruff check main.py modules_sem

[testenv:py312-ruff]
skip_install = true
deps = -rrequirements-test.txt
commands =
  ruff check main.py modules_sem
